In [11]:
import numpy as np
# creating array with arange function of numpy
a=np.arange(15)# single dimensional
print(a)
a=np.arange(15).reshape(3,5)# multi-dimensional
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# numpy array properties

In [12]:
# size of array
a.size

15

In [13]:
x=np.array([1,3,4,5,6])
print(x)

[1 3 4 5 6]


In [14]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


In [15]:
print('shape',x.shape)
print('num of dimensions:',x.ndim)
print('type of data: ',x.dtype)
print('Y')
print('shape',y.shape)
print('num of dimensions:',y.ndim)
print('type of data: ',y.dtype)

shape (5,)
num of dimensions: 1
type of data:  int32
Y
shape (2, 3)
num of dimensions: 2
type of data:  int32


- arange
- linspace
- random*
- eye
- ones
- zero

In [16]:
np.set_printoptions(precision=4, suppress=True)

In [17]:
a=np.arange(-10,10,0.2)
print(a)

[-10.   -9.8  -9.6  -9.4  -9.2  -9.   -8.8  -8.6  -8.4  -8.2  -8.   -7.8
  -7.6  -7.4  -7.2  -7.   -6.8  -6.6  -6.4  -6.2  -6.   -5.8  -5.6  -5.4
  -5.2  -5.   -4.8  -4.6  -4.4  -4.2  -4.   -3.8  -3.6  -3.4  -3.2  -3.
  -2.8  -2.6  -2.4  -2.2  -2.   -1.8  -1.6  -1.4  -1.2  -1.   -0.8  -0.6
  -0.4  -0.2  -0.    0.2   0.4   0.6   0.8   1.    1.2   1.4   1.6   1.8
   2.    2.2   2.4   2.6   2.8   3.    3.2   3.4   3.6   3.8   4.    4.2
   4.4   4.6   4.8   5.    5.2   5.4   5.6   5.8   6.    6.2   6.4   6.6
   6.8   7.    7.2   7.4   7.6   7.8   8.    8.2   8.4   8.6   8.8   9.
   9.2   9.4   9.6   9.8]


In [18]:
b=np.linspace(0,1,10)
print(b)

[0.     0.1111 0.2222 0.3333 0.4444 0.5556 0.6667 0.7778 0.8889 1.    ]


In [19]:
np.random.random((3,3))

array([[0.3491, 0.2702, 0.1766],
       [0.4338, 0.955 , 0.1564],
       [0.003 , 0.7128, 0.5869]])

In [20]:
np.random.randint(1,1000,(3,3))

array([[527, 814, 612],
       [549, 380, 367],
       [891,  44, 847]])

In [21]:
np.eye(5, dtype=int)#identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [22]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

# mathmatical operations
- arithmatic
- statistical
- trignonometry

In [25]:
x=np.random.randint(1,25,(2,3))
y=np.random.randint(1,25,(3,2))
print(x)
print(y)

[[ 1 22 10]
 [16  2 17]]
[[ 4  2]
 [16  3]
 [ 5 11]]


In [26]:
y=y.T
print(y)
print(x)

[[ 4 16  5]
 [ 2  3 11]]
[[ 1 22 10]
 [16  2 17]]


In [27]:
print(x+y)
y=y.T

[[ 5 38 15]
 [18  5 28]]


In [28]:
x*y.T # matrix multiplication

array([[  4, 352,  50],
       [ 32,   6, 187]])

In [29]:
q= np.array([[1,2,3],[4,5,6]])
print(q)
w= np.ones((3,2),dtype=int)
print(w)
print(q@w)#normal matrix multiplication
e= np.ones((2,3),dtype=int)
print(e)
print(q*e) # corressponding same index no.s get multiplied

[[1 2 3]
 [4 5 6]]
[[1 1]
 [1 1]
 [1 1]]
[[ 6  6]
 [15 15]]
[[1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]]


In [30]:
print(x@y)#matrix multiplication as in maths

[[406 178]
 [181 225]]


In [31]:
np.hstack((x,x,x,x))

array([[ 1, 22, 10,  1, 22, 10,  1, 22, 10,  1, 22, 10],
       [16,  2, 17, 16,  2, 17, 16,  2, 17, 16,  2, 17]])

In [32]:
np.vstack((x,x,x))

array([[ 1, 22, 10],
       [16,  2, 17],
       [ 1, 22, 10],
       [16,  2, 17],
       [ 1, 22, 10],
       [16,  2, 17]])

In [33]:
print(x)
print("sum of all elements :",x.sum())
print("sum of all elements row wise :",x.sum(axis=1))
print("sum of all elements col. wise :",x.sum(axis=0))
print("mean of all elements :",x.mean())
print("meadian of all elements :",np.median(x))
print("minimum of all elements :",x.min())
print("maximum of all elements :",x.max())
print("vaiance of all elements :",x.var())
print("standard deviation of all elements :",x.std())
print("any item is non-zero :",x.any())
print("all item is non-zero :",x.all())

[[ 1 22 10]
 [16  2 17]]
sum of all elements : 68
sum of all elements row wise : [33 35]
sum of all elements col. wise : [17 24 27]
mean of all elements : 11.333333333333334
meadian of all elements : 13.0
minimum of all elements : 1
maximum of all elements : 22
vaiance of all elements : 60.55555555555555
standard deviation of all elements : 7.781745019952501
any item is non-zero : True
all item is non-zero : True


In [34]:
print(np.pi)
print(np.nan)#?
print(np.inf)#?
print(np.e)

3.141592653589793
nan
inf
2.718281828459045


In [35]:
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))


[[ 0.8415 -0.0089 -0.544 ]
 [-0.2879  0.9093 -0.9614]]
[[ 0.5403 -1.     -0.8391]
 [-0.9577 -0.4161 -0.2752]]
[[ 1.5574  0.0089  0.6484]
 [ 0.3006 -2.185   3.4939]]


In [40]:
x[x>5].reshape(2,2) # boolean filter

array([[22, 10],
       [16, 17]])

In [42]:
x=np.random.randint(-3,3,(5,5))
print(x)

[[ 1  1  0  0  0]
 [-2  2  1  2  2]
 [-2  2  2 -1  0]
 [-1  2 -2 -2  1]
 [ 1 -2 -1  1 -2]]


In [46]:
x[(x> -2) & (x<2)]

array([ 1,  1,  0,  0,  0,  1, -1,  0, -1,  1,  1, -1,  1])

In [44]:
x[(x> -2) | (x<2)]

array([ 1,  1,  0,  0,  0, -2,  2,  1,  2,  2, -2,  2,  2, -1,  0, -1,  2,
       -2, -2,  1,  1, -2, -1,  1, -2])

# indexing and slicing

In [48]:
x[0,0]

1

syntax for slicing in 1d: :[start:stop:step]
syntax for slicing in 1d: :[rstart:rstop:rstep,cstart:cstop:cstep]

In [53]:
print(x[0])
print(x[-1])
print(x)

[1 1 0 0 0]
[ 1 -2 -1  1 -2]
[[ 1  1  0  0  0]
 [-2  2  1  2  2]
 [-2  2  2 -1  0]
 [-1  2 -2 -2  1]
 [ 1 -2 -1  1 -2]]


In [57]:
print(x[0,:3])# : here column implies all elements of that perticular row or column
print(x[0,-4:])
print(x[-1,])
print(x[:-1,-1])
print(x[:,:2])# x[rstart : rend ,cstart:ccolumn]      
print(x[:,[2,4,1,3]])# 2,4,1,3 index column

[1 1 0]
[1 0 0 0]
[ 1 -2 -1  1 -2]
[0 2 0 1]
[[ 1  1]
 [-2  2]
 [-2  2]
 [-1  2]
 [ 1 -2]]
[[ 0  0  1  0]
 [ 1  2  2  2]
 [ 2  0  2 -1]
 [-2  1  2 -2]
 [-1 -2 -2  1]]


# sorting

In [59]:
x.sort(axis=0)
x

array([[-2, -2, -2, -2, -2],
       [-2,  1, -1, -1,  0],
       [-1,  2,  0,  0,  0],
       [ 1,  2,  1,  1,  1],
       [ 1,  2,  2,  2,  2]])

In [73]:
x=np.random.randint(1,10,(3,3))
x

array([[5, 7, 1],
       [6, 2, 6],
       [1, 5, 3]])

In [74]:
x.sort(axis=0)# column wise sorting
print(x)
x.sort(axis=1)# column wise sorting
print(x)

[[1 2 1]
 [5 5 3]
 [6 7 6]]
[[1 1 2]
 [3 5 5]
 [6 6 7]]


In [75]:
x = x.flatten()
x.sort()
print(x)

[1 1 2 3 5 5 6 6 7]


In [77]:
print(x.argmax()) # return index of max element
print(x.argmin()) # return index of min element

8
0
